# Generated by Django 3.2.15 on 2022-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('seats', models.CharField(choices=[('Two', '2 SEATS'), ('Four', '4 SEATS'), ('Eight', '8 SEATS')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
